[dev]
command = "vite"
autoLaunch = false

[build]
command = "bun run predeploy"
publish = "dist"

[images]
remote_images = [
	"http://127.0.0.1:3210/api/storage/.*",
	"https://elegant-eel-777.convex.site/.*",
	"https://elegant-eel-777.convex.cloud/api/storage/.*",
]
